export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL="CREATE_ORDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ORDER_LIST_MY_REQUEST='ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS='ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAILS='ORDER_LIST_MY_FAILS';

export const ORDER_DETAILS_REQUEST='ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS='ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAILS='ORDER_DETAILS_FAILS';
export const ORDER_DETAILS_RESET='ORDER_DETAILS_RESET';